# add the linters you want stickler to use for this project
linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './eslint.config'
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"
# add the files here you want to be ignored by stylelint
files:
  ignore:
      - 'dist/*'
      - "Guardfile"
      - "Rakefile"
      - "node_modules/**/*"
      - "db/**"
      - "config/**"